name: Release

on:
  workflow_run:
    workflows: [ 'Build' ]
    branches: [ 'release/*' ]
    types: [ completed ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release name
        id: release_name
        uses: actions/github-script@v4
        with:
          script: |
            const version = $GITHUB_REF.substring(8,$GITHUB_REF.length -1)
          value: version
